import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'pt';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation data
const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.services': 'Services',
    'nav.training': 'Training',
    'nav.clinical': 'Clinical',
    'nav.research': 'Research',
    'nav.digital': 'Digital Development',
    'nav.publishing': 'Acendalha Publishing',
    'nav.team': 'Team',
    'nav.contacts': 'Contacts',
    
    // Home page
    'home.hero.title': 'Unbreakable Idea Research',
    'home.hero.subtitle': 'Advancing Health Through Innovation, Research, and Education',
    'home.hero.services': 'Our Services',
    'home.hero.learn': 'Learn More',
    'home.expertise.title': 'Our Areas of Expertise',
    'home.expertise.subtitle': 'Comprehensive solutions for health research, education, and innovation',
    'home.research.title': 'Research Activities',
    'home.research.desc': 'Quantitative & qualitative research, statistical analysis, and data visualization',
    'home.training.title': 'Training Programs',
    'home.training.desc': 'Leadership development, health communication, and research methodology training',
    'home.clinical.title': 'Clinical Services',
    'home.clinical.desc': 'Cognitive-behavioral therapy, psychological assessment, and specialized treatments',
    'home.digital.title': 'Digital Environment',
    'home.digital.desc': 'Health-related software and digital solutions to enhance healthcare delivery and research capabilities',
    'home.editorial.title': 'Editorial Services',
    'home.editorial.desc': 'Scientific and science-fiction publishing through Acendalha Publishing',
    'home.innovation.title': 'Leading Innovation in Health Research',
    'home.innovation.desc1': 'Under the leadership of CEO Osvaldo Santos, a renowned clinical and health psychologist and researcher, UBKIR combines cutting-edge research methodologies with practical applications in healthcare, education, and digital innovation.',
    'home.innovation.desc2': 'Our multidisciplinary approach ensures comprehensive solutions that bridge the gap between academic research and real-world healthcare challenges.',
    'home.innovation.team': 'Meet Our Team',
    'home.stats.years': 'Years of Experience',
    'home.stats.projects': 'Research Projects',
    'home.cta.title': 'Ready to Collaborate?',
    'home.cta.desc': 'Let\'s discuss how our expertise can support your research, training, or clinical needs.',
    'home.cta.contact': 'Get in Touch',
    
    // About page
    'about.title': 'About UBKIR',
    'about.subtitle': 'Pioneering Research and Innovation in Health Sciences',
    'about.mission.title': 'Our Mission',
    'about.mission.desc': 'To advance health sciences through innovative research methodologies, evidence-based training programs, and comprehensive clinical services that bridge the gap between academic excellence and practical healthcare solutions.',
    'about.vision.title': 'Our Vision',
    'about.vision.desc': 'To be a leading research organization that transforms healthcare delivery through cutting-edge research, education, and digital innovation, contributing to improved health outcomes globally.',
    'about.values.title': 'Our Values',
    'about.values.excellence': 'Scientific Excellence',
    'about.values.excellence.desc': 'Commitment to rigorous research methodologies and evidence-based practices',
    'about.values.innovation': 'Innovation',
    'about.values.innovation.desc': 'Embracing new technologies and methodologies to solve complex health challenges',
    'about.values.collaboration': 'Collaboration',
    'about.values.collaboration.desc': 'Building partnerships with healthcare professionals, researchers, and institutions',
    'about.values.integrity': 'Integrity',
    'about.values.integrity.desc': 'Maintaining the highest ethical standards in all our research and clinical activities',
    
    // About page - Our Story section
    'about.story.title': 'Our Story',
    'about.story.p1': 'Founded with the vision of creating unbreakable connections between research, education, and clinical practice, UBKIR has grown into a multidisciplinary organization that serves clients across Portugal and internationally.',
    'about.story.p2': 'We combine local expertise with global perspectives, offering comprehensive services that span from individual psychological support to large-scale research initiatives and professional training programs.',
    'about.story.p3': 'Our diverse portfolio includes quantitative and qualitative research, statistical analysis, psychometric evaluation, clinical psychology services, professional training, and editorial services through our Acendalha Publishing division.',
    
    // About page - Areas of Specialization
    'about.specializations.title': 'Areas of Specialization',
    'about.spec.quantResearch': 'Quantitative Research & Surveys',
    'about.spec.qualResearch': 'Qualitative Research & Focus Groups',
    'about.spec.statAnalysis': 'Statistical Analysis & Data Visualization',
    'about.spec.psychometric': 'Psychometric Analysis',
    'about.spec.realWorld': 'Real World Evidence Research',
    'about.spec.marketing': 'Marketing Research',
    'about.spec.healthComm': 'Health Communication Training',
    'about.spec.leadership': 'Leadership Development',
    'about.spec.cbt': 'Cognitive-Behavioral Therapy',
    'about.spec.eatingDisorders': 'Eating Disorders Treatment',
    'about.spec.chronicDisease': 'Chronic Disease Management',
    'about.spec.publishing': 'Scientific Publishing',
    
    // Services page
    'services.title': 'Our Services',
    'services.subtitle': 'Comprehensive solutions for health research, training, and clinical practice',
    'services.research.title': 'Research Activities',
    'services.research.quant': 'Quantitative Research',
    'services.research.quant.desc': 'Surveys, statistical analysis, and data visualization including dashboard development',
    'services.research.qual': 'Qualitative Research',
    'services.research.qual.desc': 'Focus groups, in-depth interviews, World Cafés, and consensus-building through Delphi panels',
    'services.research.specialized': 'Specialized Research',
    'services.research.specialized.desc': 'Psychometric analysis, real-world evidence research, and marketing research',
    'services.research.evidence.desc': 'Evidence-based research solutions using advanced methodologies and cutting-edge analytics.',
    'team.leading.expert': 'Leading Expert in',
    'team.health.psychology': 'Health Psychology',
    'services.training.title': 'Training Programs',
    'services.training.leadership': 'Leadership Development',
    'services.training.leadership.desc': 'Specialized programs for health professionals teams and healthcare management',
    'services.training.communication': 'Health Communication',
    'services.training.communication.desc': 'Develop essential leadership skills for healthcare professionals and team management.',
    'services.training.methods': 'Research Methods',
    'services.training.methods.desc': 'Comprehensive training in qualitative and quantitative research methodologies',
    'services.clinical.title': 'Clinical Services',
    'services.clinical.therapy': 'Cognitive-Behavioral Therapy',
    'services.clinical.therapy.desc': 'Evidence-based therapeutic interventions for various psychological conditions',
    'services.clinical.specialized': 'Specialized Treatments',
    'services.clinical.specialized.desc': 'Eating disorders, depression, anxiety, chronic disease adjustment, and couple therapy',
    'services.digital.title': 'Digital Development',
    'services.digital.desc': 'Health-related software and digital solutions to enhance healthcare delivery and research capabilities',
    'services.publishing.title': 'Acendalha Publishing',
    'services.publishing.desc': 'Editorial services for scientific publications and science-fiction literature',
    
    // Services page - Research examples
    'services.research.examples.survey': 'Survey design and implementation',
    'services.research.examples.statistical': 'Statistical analysis and modeling',
    'services.research.examples.visualization': 'Data visualization and dashboards',
    'services.research.examples.epidemiological': 'Epidemiological studies',
    'services.research.examples.focus': 'Focus group facilitation',
    'services.research.examples.interviews': 'In-depth interviews',
    'services.research.examples.worldcafe': 'World Café methodology',
    'services.research.examples.thematic': 'Thematic analysis',
    'services.research.examples.delphi': 'Consensus methods (Delphi, Nominal Groups, etc.)',
    'services.research.examples.psychometric': 'Psychometric validation',
    'services.research.examples.realworld': 'Real-world evidence studies',
    'services.research.examples.marketing': 'Market research and analysis',
    'services.research.examples.behavioral': 'Behavioral research',
    
    // Services page - Training examples
    'services.training.desc': 'Professional development programs designed to enhance skills and knowledge in healthcare and research.',
    'services.training.adherence.example': 'Treatment Adherence Promotion',
    'services.training.adherence.desc': 'Evidence-based strategies to improve patient compliance and treatment outcomes.',
    'services.training.adherence.text': 'Learn effective techniques to enhance patient engagement and medication adherence through behavioral interventions and communication strategies.',
    'services.training.adherence.item1': 'Motivational interview',
    'services.training.adherence.item2': 'Behavioral Change',
    'services.training.adherence.item3': 'Patient Engagement',
    'services.training.communication.example': 'Communication and Leadership in Healthcare',
    'services.training.communication.text': 'Comprehensive leadership training covering team dynamics, conflict resolution, strategic planning, and effective communication in healthcare settings.',
    'services.training.communication.item1': 'Team leadership',
    'services.training.communication.item2': 'Conflict management and resolution',
    'services.training.communication.item3': 'Development and implementation of public health strategies',
    'services.training.methods.example': 'Research Methods',
    'services.training.methods.example.desc': 'Master research methods including design, qualitative approaches, and questionnaire development.',
    'services.training.methods.example.text': 'Comprehensive training in research methods from study design to questionnaire development and psychometric evaluation.',
    'services.training.methods.item1': 'Research design',
    'services.training.methods.item2': 'Qualitative research',
    'services.training.methods.item3': 'Questionnaire development: from question to psychometric evaluation',
     
    // Services page - Clinical examples
    'services.clinical.desc': 'Evidence-based psychological and clinical services for individuals and couples.',
    'services.clinical.individual.example': 'Individual Therapy',
    'services.clinical.individual.desc': 'Specialized psychological interventions using cognitive-behavioral and experiential approaches.',
    'services.clinical.individual.item1': 'Cognitive-Behavioral Therapy (CBT)',
    'services.clinical.individual.item2': 'Psychological counseling for decision-making',
    'services.clinical.individual.item3': 'Behavioral modification programs',
    'services.clinical.specialized.example': 'Specialized Services',
    'services.clinical.specialized.desc2': 'Individual and couple therapy.',
    'services.clinical.specialized.item1': 'Couple therapy',
    'services.clinical.specialized.item2': 'Psychological intervention for eating disorders treatment (anorexia, bulimia, binge eating)',
    'services.clinical.specialized.item3': 'Psychological intervention for obesity treatment',
    'services.clinical.specialized.item4': 'Psychological intervention for treatment of other chronic diseases (diabetes, cardiovascular disease, cancer)',
    'services.clinical.schedule': 'Schedule Appointment',
    'services.clinical.learnmore': 'Schedule Appointment',
    
    // Services page - Digital examples  
    'services.digital.solutions.example': 'Health Software Solutions',
    'services.digital.solutions.desc': 'Custom software development for healthcare organizations, including patient management systems, research platforms, and digital health interventions.',
    'services.digital.badge1': 'Digital Health',
    'services.digital.badge2': 'Patient Management',
    'services.digital.badge3': 'Research Platforms',
    'services.digital.badge4': 'Data Analytics',
    'services.digital.badge5': 'Mobile Health Apps',
    'services.digital.discuss': 'Discuss Your Project',
    
    // Services page - Publishing examples
    'services.publishing.excellence.example': 'Editorial Excellence',
    'services.publishing.excellence.desc': 'Acendalha Publishing specializes in high-quality scientific publications and creative science-fiction works, bridging the gap between academic rigor and accessible storytelling.',
    'services.publishing.division.example': 'Acendalha Publishing Division',
    'services.publishing.scientific': 'Scientific book publishing',
    'services.publishing.fiction': 'Science-fiction publications',
    'services.publishing.consulting': 'Editorial consulting',
    'services.publishing.manuscript': 'Manuscript development',
    'services.publishing.inquiry': 'Publishing Inquiry',
    'services.publishing.visit': 'Visit Acendalha',
    'services.publishing.division': 'Publishing Division',
    
    // Team page
    'team.title': 'Our Team',
    'team.subtitle': 'Meet the experts driving innovation at UBKIR',
    'team.expertise.title': 'Our Collective Expertise',
    'team.expertise.research': 'Research Excellence',
    'team.expertise.research.desc': 'Advanced methodologies in quantitative and qualitative research across health sciences.',
    'team.expertise.clinical': 'Clinical Practice',
    'team.expertise.clinical.desc': 'Evidence-based therapeutic interventions and psychological assessment expertise.',
    'team.expertise.training': 'Training & Education',
    'team.expertise.training.desc': 'Professional development programs and academic training in health sciences.',
    'team.expertise.publishing': 'Publishing & Innovation',
    'team.expertise.publishing.desc': 'Editorial excellence and digital innovation in health-related technologies.',
    'team.partnership.title': 'EnviHeB Lab Partnership',
    'team.partnership.desc': 'Through Osvaldo Santos\' leadership of the EnviHeB Lab, at the Institute of Environmental Health of the Lisbon School of Medicine (ISAMB-FMUL), UBKIR maintains strong connections with cutting-edge academic research and international collaboration networks.',
    'team.partnership.leadership': 'Research Leadership',
    'team.partnership.leadership.desc': 'Leading innovative research projects in environmental health and behavior.',
    'team.partnership.network': 'Academic Network',
    'team.partnership.network.desc': 'Strong connections with national and international research institutions.',
    'team.partnership.impact': 'Publication Impact', 
    'team.partnership.impact.desc': 'High-impact research publications contributing to global health knowledge.',
    'team.specializations.title': 'Professional Specializations',
    'team.cta.title': 'Work with Our Expert Team',
    'team.cta.desc': 'Ready to collaborate with leading experts in health research and clinical psychology? Contact us to discuss your project or service needs.',
    'team.cta.button': 'Start a Conversation',
    
    // Team page - Osvaldo Santos section
    'team.osvaldo.title': 'Osvaldo Santos',
    'team.osvaldo.subtitle': 'CEO & Clinical Health Psychologist',
    'team.osvaldo.bio': 'Osvaldo Santos is a distinguished clinical and health psychologist with extensive experience in clinical practice, research, and teaching. As the head of the Environmental Health Behavior Laboratory, from the Institute of Environmental Health of the Lisbon School of Medicine (ISAMB-FMUL), and one of Portugal\'s most cited psychologists, Osvaldo Santos brings unparalleled expertise to UBKIR\'s mission of advancing health through innovation and research.',
    'team.osvaldo.achievements.title': 'Key Achievements',
    'team.osvaldo.achievements.enviheb': 'Head of EnviHeB Lab at ISAMB',
    'team.osvaldo.achievements.cited': 'One of Portugal\'s most cited psychologists',
    'team.osvaldo.achievements.research': 'Extensive research in health psychology',
    'team.osvaldo.achievements.clinical': 'Clinical expertise in multiple therapeutic approaches',
    'team.osvaldo.specializations.title': 'Specializations',
    'team.osvaldo.specializations.clinical': 'Clinical Psychology',
    'team.osvaldo.specializations.health': 'Health Psychology Research',
    'team.osvaldo.specializations.leadership': 'Academic Leadership',
    'team.osvaldo.specializations.methodology': 'Research Methodology',
    
    // Team page - Professional Specializations
    'team.prof.spec.clinical': 'Clinical Psychology',
    'team.prof.spec.health': 'Health Psychology',
    'team.prof.spec.research': 'Research Methods',
    'team.prof.spec.cbt': 'Cognitive-Behavioral Therapy',
    'team.prof.spec.psychometric': 'Psychometric Assessment',
    'team.prof.spec.statistical': 'Statistical Analysis',
    'team.prof.spec.qualitative': 'Qualitative Research',
    'team.prof.spec.quantitative': 'Quantitative Research',
    'team.prof.spec.training': 'Professional Training',
    'team.prof.spec.leadership': 'Leadership Development',
    'team.prof.spec.communication': 'Health Communication',
    'team.prof.spec.digital': 'Digital Health Solutions',
    
    // Contacts page
    'contacts.title': 'Contact Us',
    'contacts.subtitle': 'Get in touch with our team',
    'contacts.office.title': 'Visit Our Office',
    'contacts.office.address': 'Address',
    'contacts.map.placeholder': 'Interactive map with satellite view coming soon',
    'contacts.map.note': '(Requires Supabase integration for full functionality)',
    'contacts.info.title': 'Contact Information',
    'contacts.email': 'Email',
    'contacts.hours.title': 'Business Hours',
    'contacts.hours.monday': 'Monday - Friday: 10:00 AM - 5:00 PM',
    'contacts.hours.saturday': 'Saturday: Closed',
    'contacts.hours.sunday': 'Sunday: Closed',
    'contacts.general.title': 'General Inquiry',
    'contacts.general.desc': 'Send us a message about our services or general questions.',
    'contacts.alert': 'Email functionality requires Supabase integration to be fully operational.',
    'contacts.form.firstName': 'First Name',
    'contacts.form.lastName': 'Last Name',
    'contacts.form.firstName.placeholder': 'Your first name',
    'contacts.form.lastName.placeholder': 'Your last name',
    'contacts.form.email': 'Email Address',
    'contacts.form.email.placeholder': 'your.email@example.com',
    'contacts.form.subject': 'Subject',
    'contacts.form.subject.placeholder': 'Select inquiry type',
    'contacts.form.subject.research': 'Research Services',
    'contacts.form.subject.training': 'Training Programs',
    'contacts.form.subject.clinical': 'Clinical Services',
    'contacts.form.subject.digital': 'Digital Development',
    'contacts.form.subject.publishing': 'Publishing Services',
    'contacts.form.subject.collaboration': 'Collaboration',
    'contacts.form.subject.other': 'Other',
    'contacts.form.message': 'Message',
    'contacts.form.message.placeholder': 'Tell us about your project or inquiry...',
    'contacts.form.send': 'Send Message',
    'contacts.training.enroll': 'Learn More/Enrollment',
    'contacts.training.enrollment': 'Training Program Enrollment',
    'contacts.training.enrollment.desc': 'Register your interest in our professional training programs.',
    'contacts.training.name': 'Full Name',
    'contacts.training.name.placeholder': 'Your full name',
    'contacts.training.email.placeholder': 'your.email@example.com',
    'contacts.training.organization': 'Organization',
    'contacts.training.organization.placeholder': 'Your organization or institution',
    'contacts.training.program': 'Select Program',
    'contacts.training.program.placeholder': 'Select training program',
    'contacts.training.adherence': 'Promotion of Treatment Adherence',
    'contacts.training.leadership': 'Communication and leadership in healthcare',
    'contacts.training.research': 'Research methods',
    'contacts.training.qualitative': 'Qualitative Research Methods',
    'contacts.training.custom': 'Custom Training (specify in comments)',
    'contacts.training.comments': 'Additional Comments',
    'contacts.training.comments.placeholder': 'Any specific requirements or questions about the training?',
    'contacts.training.submit': 'Submit Enrollment',
    'contacts.cta.title': 'Ready to Start Your Project?',
    'contacts.cta.desc': 'Whether you need research support, training programs, clinical services, or digital solutions, our team is ready to help you achieve your goals with evidence-based approaches.',
    'contacts.response.title': 'Quick Response',
    'contacts.response.desc': 'We typically respond to inquiries within 24 hours during business days.',
    'contacts.direct.title': 'Direct Communication',
    'contacts.direct.desc': 'Reach out directly to info@ubkir.pt for immediate assistance.',
    'contacts.visit.title': 'Visit Us',
    'contacts.visit.desc': 'Schedule an in-person consultation at our Painho office.',
    
    // Footer
    'footer.company': 'UBKIR',
    'footer.description': 'Unbreakable Idea Research - Advancing Health Through Innovation, Research, and Education',
    'footer.contactInfo': 'Contact Info',
    'footer.services': 'Services',
    'footer.research': 'Research Activities',
    'footer.training': 'Training Programs',
    'footer.clinical': 'Clinical Services',
    'footer.software': 'Digital Development',
    'footer.editorial': 'Editorial Services',
    'footer.rights': '© 2024 Unbreakable Idea Research. All rights reserved.',
  },
  pt: {
    // Navigation
    'nav.home': 'Início',
    'nav.about': 'Sobre Nós',
    'nav.services': 'Serviços',
    'nav.training': 'Formação',
    'nav.clinical': 'Clínica',
    'nav.research': 'Investigação',
    'nav.digital': 'Desenvolvimento Digital',
    'nav.publishing': 'Publicação Acendalha',
    'nav.team': 'Equipa',
    'nav.contacts': 'Contactos',
    
    // Home page
    'home.hero.title': 'Unbreakable Idea Research',
    'home.hero.subtitle': 'Promovendo a Saúde Através da Inovação, Investigação e Educação',
    'home.hero.services': 'Os Nossos Serviços',
    'home.hero.learn': 'Saber Mais',
    'home.expertise.title': 'As Nossas Áreas de Especialização',
    'home.expertise.subtitle': 'Soluções abrangentes para investigação em saúde, educação e inovação',
    'home.research.title': 'Investigação',
    'home.research.desc': 'Investigação quantitativa e qualitativa, análise estatística e visualização de dados',
    'home.training.title': 'Formação',
    'home.training.desc': 'Desenvolvimento de liderança, comunicação em saúde e formação em métodos de investigação',
    'home.clinical.title': 'Serviços Clínicos',
    'home.clinical.desc': 'Terapia cognitivo-comportamental, avaliação psicológica e tratamentos especializados',
    'home.digital.title': 'Software',
    'home.digital.desc': 'Software relacionado com saúde e soluções digitais para melhorar a prestação de cuidados de saúde e capacidades de investigação',
    'home.editorial.title': 'Serviços Editoriais',
    'home.editorial.desc': 'Publicação científica e de ficção científica através da Acendalha Publishing',
    'home.innovation.title': 'Liderando a Inovação na Investigação em Saúde',
    'home.innovation.desc1': 'Sob a liderança do CEO Osvaldo Santos, um reconhecido psicólogo clínico e da saúde, e investigador, a UBKIR combina metodologias de investigação de vanguarda com aplicações práticas em cuidados de saúde, educação e inovação digital.',
    'home.innovation.desc2': 'A nossa abordagem multidisciplinar garante soluções abrangentes que fazem a ponte entre a investigação académica e os desafios reais dos cuidados de saúde.',
    'home.innovation.team': 'Conheça a Nossa Equipa',
    'home.stats.years': 'Anos de Experiência',
    'home.stats.projects': 'Projetos de Investigação',
    'home.cta.title': 'Pronto para Colaborar?',
    'home.cta.desc': 'Vamos discutir como a nossa experiência pode apoiar as suas necessidades de investigação, formação ou clínicas.',
    'home.cta.contact': 'Entre em Contacto',
    
    // About page
    'about.title': 'Sobre a UBKIR',
    'about.subtitle': 'Pioneiros em Investigação e Inovação nas Ciências da Saúde',
    'about.mission.title': 'A Nossa Missão',
    'about.mission.desc': 'Avançar as ciências da saúde através de metodologias de investigação inovadoras, programas de formação baseados em evidência e serviços clínicos abrangentes que fazem a ponte entre a excelência académica e as soluções práticas de cuidados de saúde.',
    'about.vision.title': 'A Nossa Visão',
    'about.vision.desc': 'Ser uma organização de investigação líder que transforma a prestação de cuidados de saúde através de investigação de ponta, educação e inovação digital, contribuindo para melhores resultados de saúde globalmente.',
    'about.values.title': 'Os Nossos Valores',
    'about.values.excellence': 'Excelência Científica',
    'about.values.excellence.desc': 'Compromisso com metodologias de investigação rigorosas e práticas baseadas em evidência',
    'about.values.innovation': 'Inovação',
    'about.values.innovation.desc': 'Abraçar novas tecnologias e metodologias para resolver desafios complexos de saúde',
    'about.values.collaboration': 'Colaboração',
    'about.values.collaboration.desc': 'Construir parcerias com profissionais de saúde, investigadores e instituições',
    'about.values.integrity': 'Integridade',
    'about.values.integrity.desc': 'Manter os mais altos padrões éticos em todas as nossas atividades de investigação e clínicas',
    
    // About page - Our Story section (Portuguese)
    'about.story.title': 'A Nossa História',
    'about.story.p1': 'Fundada com a visão de criar ligações inquebráveis entre investigação, educação e prática clínica, a UBKIR cresceu numa organização multidisciplinar que serve clientes em Portugal e internacionalmente.',
    'about.story.p2': 'Combinamos experiência local com perspetivas globais, oferecendo serviços abrangentes que vão desde apoio psicológico individual a iniciativas de investigação em larga escala e programas de formação profissional.',
    'about.story.p3': 'O nosso portfólio diversificado inclui investigação quantitativa e qualitativa, análise estatística, avaliação psicométrica, serviços de psicologia clínica, formação profissional e serviços editoriais através da nossa divisão Acendalha Publishing.',
    
    // About page - Areas of Specialization (Portuguese)
    'about.specializations.title': 'Áreas de Especialização',
    'about.spec.quantResearch': 'Investigação Quantitativa e Inquéritos',
    'about.spec.qualResearch': 'Investigação Qualitativa e Grupos Focais',
    'about.spec.statAnalysis': 'Análise Estatística e Visualização de Dados',
    'about.spec.psychometric': 'Análise Psicométrica',
    'about.spec.realWorld': 'Investigação de Evidência do Mundo Real',
    'about.spec.marketing': 'Investigação de Marketing',
    'about.spec.healthComm': 'Formação em Comunicação em Saúde',
    'about.spec.leadership': 'Desenvolvimento de Liderança',
    'about.spec.cbt': 'Terapia Cognitivo-Comportamental',
    'about.spec.eatingDisorders': 'Tratamento de Distúrbios Alimentares',
    'about.spec.chronicDisease': 'Gestão de Doenças Crónicas',
    'about.spec.publishing': 'Publicação Científica',
    
    // Services page
    'services.title': 'Os Nossos Serviços',
    'services.subtitle': 'Soluções abrangentes para investigação em saúde, formação e prática clínica',
    'services.research.title': 'Atividades de Investigação',
    'services.research.quant': 'Investigação Quantitativa',
    'services.research.quant.desc': 'Inquéritos, análise estatística e visualização de dados incluindo desenvolvimento de dashboards',
    'services.research.qual': 'Investigação Qualitativa',
    'services.research.qual.desc': 'Grupos focais, entrevistas em profundidade, World Cafés e construção de consenso através de métodos de consenso',
    'services.research.specialized': 'Investigação Especializada',
    'services.research.specialized.desc': 'Análise psicométrica, investigação de evidência do mundo real e investigação de marketing',
    'services.research.evidence.desc': 'Soluções de investigação baseadas em evidência utilizando metodologias avançadas e análises de ponta.',
    'team.leading.expert': 'Especialista Reconhecido em',
    'team.health.psychology': 'Psicologia da Saúde',
    'services.training.title': 'Programas de Formação',
    'services.training.desc': 'Programas de desenvolvimento profissional para melhorar competências e conhecimentos em cuidados de saúde e investigação.',
    'services.training.leadership': 'Desenvolvimento de Liderança',
    'services.training.leadership.desc': 'Programas especializados para equipas de profissionais de saúde e gestão de cuidados de saúde',
    'services.training.communication': 'Comunicação em Saúde',
    'services.training.methods': 'Métodos de Investigação',
    'services.clinical.title': 'Serviços Clínicos',
    'services.clinical.desc': 'Serviços psicológicos e clínicos baseados em evidência para indivíduos e casais.',
    'services.clinical.therapy': 'Terapia Cognitivo-Comportamental',
    'services.clinical.therapy.desc': 'Intervenções terapêuticas baseadas em evidência para várias condições psicológicas',
    'services.clinical.specialized': 'Tratamentos Especializados',
    'services.clinical.specialized.desc': 'Distúrbios alimentares, depressão, ansiedade, adaptação a doenças crónicas e terapia de casal',
    'services.digital.title': 'Desenvolvimento Digital',
    'services.digital.desc': 'Software relacionado com saúde e soluções digitais para melhorar a prestação de cuidados de saúde e capacidades de investigação',
    'services.publishing.title': 'Publicação Acendalha',
    'services.publishing.desc': 'Serviços editoriais para publicações científicas e literatura de ficção científica',
    
    // Services page - Research examples (Portuguese)
    'services.research.examples.survey': 'Conceção e implementação de inquéritos',
    'services.research.examples.statistical': 'Análise estatística e modelação',
    'services.research.examples.visualization': 'Visualização de dados e dashboards',
    'services.research.examples.epidemiological': 'Estudos epidemiológicos',
    'services.research.examples.focus': 'Facilitação de grupos focais',
    'services.research.examples.interviews': 'Entrevistas em profundidade',
    'services.research.examples.worldcafe': 'Metodologia World Café',
    'services.research.examples.thematic': 'Análise temática',
    'services.research.examples.delphi': 'Métodos de consenso (Delphi, Grupos nominais, etc.)',
    'services.research.examples.psychometric': 'Validação psicométrica',
    'services.research.examples.realworld': 'Estudos de evidência do mundo real',
    'services.research.examples.marketing': 'Investigação e análise de mercado',
    'services.research.examples.behavioral': 'Investigação comportamental',
    
    // Services page - Training examples (Portuguese)
    'services.training.adherence.example': 'Promoção da Adesão ao Tratamento',
    'services.training.adherence.desc': 'Estratégias baseadas em evidência para melhorar a adesão dos doentes e os resultados do tratamento.',
    'services.training.adherence.text': 'Aprenda técnicas eficazes para aumentar o envolvimento dos doentes e a adesão à medicação através de intervenções comportamentais e estratégias de comunicação.',
    'services.training.adherence.item1': 'Entrevista motivacional',
    'services.training.adherence.item2': 'Mudança comportamental',
    'services.training.adherence.item3': 'Envolvimento do doente',
    'services.training.communication.example': 'Comunicação e Liderança em Cuidados de Saúde',
    'services.training.communication.desc': 'Desenvolva competências essenciais de liderança para profissionais de saúde e gestão de equipas.',
    'services.training.communication.text': 'Formação abrangente em liderança que abrange dinâmicas de equipa, resolução de conflitos, planeamento estratégico e comunicação eficaz em contextos de cuidados de saúde.',
    'services.training.communication.item1': 'Liderança de equipas',
    'services.training.communication.item2': 'Gestão e resolução de conflitos',
    'services.training.communication.item3': 'Desenvolvimento e implementação de estratégias de saúde pública',
    'services.training.methods.desc': 'Domine métodos de investigação incluindo desenho, abordagens qualitativas e desenvolvimento de questionários.',
    'services.training.methods.text': 'Formação abrangente em métodos de investigação desde o desenho de estudos ao desenvolvimento de questionários e avaliação psicométrica.',
    'services.training.methods.item1': 'Desenho de investigação',
    'services.training.methods.item2': 'Investigação qualitativa',
    'services.training.methods.item3': 'Desenvolvimento de questionários: desde a questão à avaliação psicométrica',
    
    // Services page - Clinical examples (Portuguese)
    'services.clinical.individual.example': 'Terapia Individual',
    'services.clinical.individual.desc': 'Intervenções psicológicas especializadas usando abordagens cognitivo-comportamentais e experienciais.',
    'services.clinical.individual.item1': 'Terapia Cognitivo-Comportamental (TCC)',
    'services.clinical.individual.item2': 'Aconselhamento psicológico para tomada de decisão',
    'services.clinical.individual.item3': 'Programas de modificação comportamental',
    'services.clinical.schedule': 'Agendar Consulta',
    'services.clinical.specialized.example': 'Serviços Especializados',
    'services.clinical.specialized.desc2': 'Terapia individual e de casal.',
    'services.clinical.specialized.item1': 'Terapia de casal',
    'services.clinical.specialized.item2': 'Intervenção psicológica para tratamento de distúrbios alimentares (anorexia, bulimia, compulsão alimentar)',
    'services.clinical.specialized.item3': 'Intervenção psicológica para tratamento da obesidade',
    'services.clinical.specialized.item4': 'Intervenção psicológica para tratamento de outras doenças crónicas (diabetes, doença cardiovascular, cancro)',
    'services.clinical.learnmore': 'Agendar consulta',
    
    // Services page - Digital examples (Portuguese)
    'services.digital.solutions.example': 'Soluções de Software de Saúde',
    'services.digital.solutions.desc': 'Desenvolvimento de software personalizado para organizações de saúde, incluindo sistemas de gestão de doentes, plataformas de investigação e intervenções de saúde digital.',
    'services.digital.badge1': 'Saúde Digital',
    'services.digital.badge2': 'Gestão de Doentes',
    'services.digital.badge3': 'Plataformas de Investigação',
    'services.digital.badge4': 'Análise de Dados',
    'services.digital.badge5': 'Aplicações de Saúde Móvel',
    'services.digital.discuss': 'Discutir o Seu Projeto',
    
    // Services page - Publishing examples (Portuguese)
    'services.publishing.excellence.example': 'Excelência Editorial',
    'services.publishing.excellence.desc': 'A Acendalha especializa-se em publicações científicas de elevada qualidade e em obras criativas de ficção científica, aproximando o rigor académico de uma linguagem acessível.',
    'services.publishing.division.example': 'Divisão de Publicação Acendalha',
    'services.publishing.scientific': 'Publicação de livros científicos',
    'services.publishing.fiction': 'Publicações de ficção científica',
    'services.publishing.consulting': 'Consultoria editorial',
    'services.publishing.manuscript': 'Desenvolvimento de manuscritos',
    'services.publishing.inquiry': 'Consulta de Publicação',
    'services.publishing.visit': 'Visitar a Acendalha',
    'services.publishing.division': 'Divisão de Publicação',
    
    // Team page
    'team.title': 'A Nossa Equipa',
    'team.subtitle': 'Conheça os especialistas que impulsionam a inovação na UBKIR',
    'team.expertise.title': 'A Nossa Especialização Coletiva',
    'team.expertise.research': 'Excelência em Investigação',
    'team.expertise.research.desc': 'Métodos avançados em investigação quantitativa e qualitativa nas ciências da saúde.',
    'team.expertise.clinical': 'Prática Clínica',
    'team.expertise.clinical.desc': 'Intervenções terapêuticas baseadas em evidência e experiência em avaliação psicológica.',
    'team.expertise.training': 'Formação e Educação',
    'team.expertise.training.desc': 'Programas de desenvolvimento profissional e formação académica em ciências da saúde.',
    'team.expertise.publishing': 'Publicação e Inovação',
    'team.expertise.publishing.desc': 'Excelência editorial e inovação digital em tecnologias relacionadas com a saúde.',
    'team.partnership.title': 'Parceria com o Laboratório EnviHeB',
    'team.partnership.desc': 'Através da liderança por Osvaldo Santos do Laboratório EnviHeB, do Instituto de Saúde Ambiental da Faculdade de Medicina da Universidade de Lisboa (SAMB-FMUL), a UBKIR  mantém fortes conexões com investigação de ponta na área da saúde, e da saúde ambiental, garantindo também redes de colaboração internacional.',
    'team.partnership.leadership': 'Liderança em Investigação',
    'team.partnership.leadership.desc': 'Liderar projetos de investigação inovadores em saúde ambiental e comportamento.',
    'team.partnership.network': 'Rede Académica',
    'team.partnership.network.desc': 'Fortes conexões com instituições de investigação nacionais e internacionais.',
    'team.partnership.impact': 'Impacto das Publicações',
    'team.partnership.impact.desc': 'Publicações de investigação de alto impacto que contribuem para o conhecimento global da saúde.',
    'team.specializations.title': 'Especializações Profissionais',
    'team.cta.title': 'Trabalhe com a Nossa Equipa de Especialistas',
    'team.cta.desc': 'Pronto para colaborar com especialistas líderes em investigação em saúde e psicologia clínica? Contacte-nos para discutir as suas necessidades de projeto ou serviço.',
    'team.cta.button': 'Iniciar uma Conversa',
    
    // Team page - Osvaldo Santos section (Portuguese)
    'team.osvaldo.title': 'Osvaldo Santos',
    'team.osvaldo.subtitle': 'CEO e Psicólogo Clínico da Saúde',
    'team.osvaldo.bio': 'Osvaldo Santos é um distinto psicólogo clínico e da saúde com vasta experiência em prática clínica, investigação e ensino. Como diretor do Laboratório de Comportamento de Saúde Ambiental (EnviHeB Lab), do Instituto de Saúde Ambiental da Faculdade de Medicina de Lisboa, e um dos psicólogos mais citados de Portugal, Osvaldo Santos traz uma experiência incomparável à missão da UBKIR de promover a saúde através da inovação e investigação.',
    'team.osvaldo.achievements.title': 'Principais Conquistas',
    'team.osvaldo.achievements.enviheb': 'Diretor do EnviHeB Lab no ISAMB',
    'team.osvaldo.achievements.cited': 'Um dos psicólogos mais citados de Portugal',
    'team.osvaldo.achievements.research': 'Vasta investigação em psicologia da saúde',
    'team.osvaldo.achievements.clinical': 'Experiência clínica em múltiplas abordagens terapêuticas',
    'team.osvaldo.specializations.title': 'Especializações',
    'team.osvaldo.specializations.clinical': 'Psicologia Clínica',
    'team.osvaldo.specializations.health': 'Investigação em Psicologia da Saúde',
    'team.osvaldo.specializations.leadership': 'Liderança Académica',
    'team.osvaldo.specializations.methodology': 'Metodologia de Investigação',
    
    // Team page - Professional Specializations (Portuguese)
    'team.prof.spec.clinical': 'Psicologia Clínica',
    'team.prof.spec.health': 'Psicologia da Saúde',
    'team.prof.spec.research': 'Métodos de Investigação',
    'team.prof.spec.cbt': 'Terapia Cognitivo-Comportamental',
    'team.prof.spec.psychometric': 'Avaliação Psicométrica',
    'team.prof.spec.statistical': 'Análise Estatística',
    'team.prof.spec.qualitative': 'Investigação Qualitativa',
    'team.prof.spec.quantitative': 'Investigação Quantitativa',
    'team.prof.spec.training': 'Formação Profissional',
    'team.prof.spec.leadership': 'Desenvolvimento de Liderança',
    'team.prof.spec.communication': 'Comunicação em Saúde',
    'team.prof.spec.digital': 'Soluções de Saúde Digital',
    
    // Contacts page
    'contacts.title': 'Contacte-nos',
    'contacts.subtitle': 'Entre em contacto com a nossa equipa',
    'contacts.office.title': 'Visite o Nosso Escritório',
    'contacts.office.address': 'Morada',
    'contacts.map.placeholder': 'Mapa interativo com vista satélite em breve',
    'contacts.map.note': '(Requer integração Supabase para funcionalidade completa)',
    'contacts.info.title': 'Informações de Contacto',
    'contacts.email': 'Email',
    'contacts.hours.title': 'Horário de Funcionamento',
    'contacts.hours.monday': 'Segunda - Sexta: 10:00 - 17:00',
    'contacts.hours.saturday': 'Sábado: Fechado',
    'contacts.hours.sunday': 'Domingo: Fechado',
    'contacts.general.title': 'Consulta Geral',
    'contacts.general.desc': 'Envie-nos uma mensagem sobre os nossos serviços ou questões gerais.',
    'contacts.alert': 'A funcionalidade de email requer integração Supabase para estar totalmente operacional.',
    'contacts.form.firstName': 'Primeiro Nome',
    'contacts.form.lastName': 'Último Nome',
    'contacts.form.firstName.placeholder': 'O seu primeiro nome',
    'contacts.form.lastName.placeholder': 'O seu último nome',
    'contacts.form.email': 'Endereço de Email',
    'contacts.form.email.placeholder': 'seu.email@exemplo.com',
    'contacts.form.subject': 'Assunto',
    'contacts.form.subject.placeholder': 'Selecionar tipo de consulta',
    'contacts.form.subject.research': 'Serviços de Investigação',
    'contacts.form.subject.training': 'Programas de Formação',
    'contacts.form.subject.clinical': 'Serviços Clínicos',
    'contacts.form.subject.digital': 'Desenvolvimento Digital',
    'contacts.form.subject.publishing': 'Serviços de Publicação',
    'contacts.form.subject.collaboration': 'Colaboração',
    'contacts.form.subject.other': 'Outro',
    'contacts.form.message': 'Mensagem',
    'contacts.form.message.placeholder': 'Conte-nos sobre o seu projeto ou consulta...',
    'contacts.form.send': 'Enviar Mensagem',
    'contacts.training.enroll': 'Saber mais/Inscrições',
    'contacts.training.enrollment': 'Inscrição em Programa de Formação',
    'contacts.training.enrollment.desc': 'Registe o seu interesse nos nossos programas de formação profissional.',
    'contacts.training.name': 'Nome Completo',
    'contacts.training.name.placeholder': 'O seu nome completo',
    'contacts.training.email.placeholder': 'seu.email@exemplo.com',
    'contacts.training.organization': 'Organização',
    'contacts.training.organization.placeholder': 'A sua organização ou instituição',
    'contacts.training.program': 'Selecionar Programa',
    'contacts.training.program.placeholder': 'Selecionar programa de formação',
    'contacts.training.adherence': 'Promoção da Adesão ao Tratamento',
    'contacts.training.leadership': 'Comunicação e liderança em cuidados de saúde',
    'contacts.training.research': 'Métodos de investigação',
    'contacts.training.qualitative': 'Métodos de Investigação Qualitativa',
    'contacts.training.custom': 'Formação Personalizada (especificar nos comentários)',
    'contacts.training.comments': 'Comentários Adicionais',
    'contacts.training.comments.placeholder': 'Algum requisito específico ou questões sobre a formação?',
    'contacts.training.submit': 'Submeter Inscrição',
    'contacts.cta.title': 'Pronto para Iniciar o Seu Projeto?',
    'contacts.cta.desc': 'Quer precise de apoio em investigação, programas de formação, serviços clínicos ou soluções digitais, a nossa equipa está pronta para o ajudar a alcançar os seus objetivos com abordagens baseadas em evidência.',
    'contacts.response.title': 'Resposta Rápida',
    'contacts.response.desc': 'Normalmente respondemos a consultas dentro de 24 horas durante os dias úteis.',
    'contacts.direct.title': 'Comunicação Direta',
    'contacts.direct.desc': 'Contacte diretamente info@ubkir.pt para assistência imediata.',
    'contacts.visit.title': 'Visite-nos',
    'contacts.visit.desc': 'Agende uma consulta presencial no nosso escritório em Painho.',
    
    // Footer
    'footer.company': 'UBKIR',
    'footer.description': 'Unbreakable Idea Research - Promovendo a Saúde Através da Inovação, Investigação e Educação',
    'footer.contactInfo': 'Informações de Contacto',
    'footer.services': 'Serviços',
    'footer.research': 'Atividades de Investigação',
    'footer.training': 'Programas de Formação',
    'footer.clinical': 'Serviços Clínicos',
    'footer.software': 'Desenvolvimento de Software',
    'footer.editorial': 'Serviços Editoriais',
    'footer.rights': '© 2024 Unbreakable Idea Research. Todos os direitos reservados.',
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('en');

  // Load language preference from localStorage on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem('ubkir-language') as Language;
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'pt')) {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('ubkir-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};