import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'pt';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation data
const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.services': 'Services',
    'nav.training': 'Training',
    'nav.clinical': 'Clinical',
    'nav.research': 'Research',
    'nav.digital': 'Digital Development',
    'nav.publishing': 'Acendalha Publishing',
    'nav.team': 'Team',
    'nav.contacts': 'Contacts',
    
    // Home page
    'home.hero.title': 'Unbreakable Idea Research',
    'home.hero.subtitle': 'Advancing Health Through Innovation, Research, and Education',
    'home.hero.services': 'Our Services',
    'home.hero.learn': 'Learn More',
    'home.expertise.title': 'Our Areas of Expertise',
    'home.expertise.subtitle': 'Comprehensive solutions for health research, education, and innovation',
    'home.research.title': 'Research Activities',
    'home.research.desc': 'Quantitative & qualitative research, statistical analysis, and data visualization',
    'home.training.title': 'Training Programs',
    'home.training.desc': 'Leadership development, health communication, and research methodology training',
    'home.clinical.title': 'Clinical Services',
    'home.clinical.desc': 'Cognitive-behavioral therapy, psychological assessment, and specialized treatments',
    'home.editorial.title': 'Editorial Services',
    'home.editorial.desc': 'Scientific and science-fiction publishing through Acendalha Publishing',
    'home.innovation.title': 'Leading Innovation in Health Research',
    'home.innovation.desc1': 'Under the leadership of CEO Osvaldo Santos, a renowned clinical and health psychologist, UBKIR combines cutting-edge research methodologies with practical applications in healthcare, education, and digital innovation.',
    'home.innovation.desc2': 'Our multidisciplinary approach ensures comprehensive solutions that bridge the gap between academic research and real-world healthcare challenges.',
    'home.innovation.team': 'Meet Our Team',
    'home.stats.years': 'Years of Experience',
    'home.stats.projects': 'Research Projects',
    'home.cta.title': 'Ready to Collaborate?',
    'home.cta.desc': 'Let\'s discuss how our expertise can support your research, training, or clinical needs.',
    'home.cta.contact': 'Get in Touch',
    
    // About page
    'about.title': 'About UBKIR',
    'about.subtitle': 'Pioneering Research and Innovation in Health Sciences',
    'about.mission.title': 'Our Mission',
    'about.mission.desc': 'To advance health sciences through innovative research methodologies, evidence-based training programs, and comprehensive clinical services that bridge the gap between academic excellence and practical healthcare solutions.',
    'about.vision.title': 'Our Vision',
    'about.vision.desc': 'To be a leading research organization that transforms healthcare delivery through cutting-edge research, education, and digital innovation, contributing to improved health outcomes globally.',
    'about.values.title': 'Our Values',
    'about.values.excellence': 'Scientific Excellence',
    'about.values.excellence.desc': 'Commitment to rigorous research methodologies and evidence-based practices',
    'about.values.innovation': 'Innovation',
    'about.values.innovation.desc': 'Embracing new technologies and methodologies to solve complex health challenges',
    'about.values.collaboration': 'Collaboration',
    'about.values.collaboration.desc': 'Building partnerships with healthcare professionals, researchers, and institutions',
    'about.values.integrity': 'Integrity',
    'about.values.integrity.desc': 'Maintaining the highest ethical standards in all our research and clinical activities',
    
    // Services page
    'services.title': 'Our Services',
    'services.subtitle': 'Comprehensive solutions for health research, training, and clinical practice',
    'services.research.title': 'Research Activities',
    'services.research.quant': 'Quantitative Research',
    'services.research.quant.desc': 'Surveys, statistical analysis, and data visualization including dashboard development',
    'services.research.qual': 'Qualitative Research',
    'services.research.qual.desc': 'Focus groups, in-depth interviews, World Cafés, and consensus-building through Delphi panels',
    'services.research.specialized': 'Specialized Research',
    'services.research.specialized.desc': 'Psychometric analysis, real-world evidence research, and marketing research',
    'services.training.title': 'Training Programs',
    'services.training.leadership': 'Leadership Development',
    'services.training.leadership.desc': 'Specialized programs for health professionals teams and healthcare management',
    'services.training.communication': 'Health Communication',
    'services.training.communication.desc': 'Effective communication strategies for healthcare settings and patient engagement',
    'services.training.methods': 'Research Methods',
    'services.training.methods.desc': 'Comprehensive training in qualitative and quantitative research methodologies',
    'services.clinical.title': 'Clinical Services',
    'services.clinical.therapy': 'Cognitive-Behavioral Therapy',
    'services.clinical.therapy.desc': 'Evidence-based therapeutic interventions for various psychological conditions',
    'services.clinical.specialized': 'Specialized Treatments',
    'services.clinical.specialized.desc': 'Eating disorders, depression, anxiety, chronic disease adjustment, and couple therapy',
    'services.digital.title': 'Digital Development',
    'services.digital.desc': 'Health-related software and digital solutions to enhance healthcare delivery and research capabilities',
    'services.publishing.title': 'Acendalha Publishing',
    'services.publishing.desc': 'Editorial services for scientific publications and science-fiction literature',
    
    // Team page
    'team.title': 'Our Team',
    'team.subtitle': 'Meet the experts driving innovation at UBKIR',
    'team.expertise.title': 'Our Collective Expertise',
    'team.expertise.research': 'Research Excellence',
    'team.expertise.research.desc': 'Advanced methodologies in quantitative and qualitative research across health sciences.',
    'team.expertise.clinical': 'Clinical Practice',
    'team.expertise.clinical.desc': 'Evidence-based therapeutic interventions and psychological assessment expertise.',
    'team.expertise.training': 'Training & Education',
    'team.expertise.training.desc': 'Professional development programs and academic training in health sciences.',
    'team.expertise.publishing': 'Publishing & Innovation',
    'team.expertise.publishing.desc': 'Editorial excellence and digital innovation in health-related technologies.',
    'team.partnership.title': 'EnviHeB Lab Partnership',
    'team.partnership.desc': 'Through Dr. Osvaldo Santos\' leadership of the EnviHeB Lab at ISAMB, UBKIR maintains strong connections with cutting-edge academic research and international collaboration networks.',
    'team.partnership.leadership': 'Research Leadership',
    'team.partnership.leadership.desc': 'Leading innovative research projects in environmental health and behavior.',
    'team.partnership.network': 'Academic Network',
    'team.partnership.network.desc': 'Strong connections with national and international research institutions.',
    'team.partnership.impact': 'Publication Impact', 
    'team.partnership.impact.desc': 'High-impact research publications contributing to global health knowledge.',
    'team.specializations.title': 'Professional Specializations',
    'team.cta.title': 'Work with Our Expert Team',
    'team.cta.desc': 'Ready to collaborate with leading experts in health research and clinical psychology? Contact us to discuss your project or service needs.',
    'team.cta.button': 'Start a Conversation',
    
    // Contacts page
    'contacts.title': 'Contact Us',
    'contacts.subtitle': 'Get in touch with our team',
    'contacts.office.title': 'Visit Our Office',
    'contacts.office.address': 'Address',
    'contacts.map.placeholder': 'Interactive map with satellite view coming soon',
    'contacts.map.note': '(Requires Supabase integration for full functionality)',
    'contacts.info.title': 'Contact Information',
    'contacts.email': 'Email',
    'contacts.hours.title': 'Business Hours',
    'contacts.hours.monday': 'Monday - Friday: 9:00 AM - 6:00 PM',
    'contacts.hours.saturday': 'Saturday: 9:00 AM - 1:00 PM',
    'contacts.hours.sunday': 'Sunday: Closed',
    'contacts.general.title': 'General Inquiry',
    'contacts.general.desc': 'Send us a message about our services or general questions.',
    'contacts.alert': 'Email functionality requires Supabase integration to be fully operational.',
    'contacts.form.firstName': 'First Name',
    'contacts.form.lastName': 'Last Name',
    'contacts.form.firstName.placeholder': 'Your first name',
    'contacts.form.lastName.placeholder': 'Your last name',
    'contacts.form.email': 'Email Address',
    'contacts.form.email.placeholder': 'your.email@example.com',
    'contacts.form.subject': 'Subject',
    'contacts.form.subject.placeholder': 'Select inquiry type',
    'contacts.form.subject.research': 'Research Services',
    'contacts.form.subject.training': 'Training Programs',
    'contacts.form.subject.clinical': 'Clinical Services',
    'contacts.form.subject.digital': 'Digital Development',
    'contacts.form.subject.publishing': 'Publishing Services',
    'contacts.form.subject.collaboration': 'Collaboration',
    'contacts.form.subject.other': 'Other',
    'contacts.form.message': 'Message',
    'contacts.form.message.placeholder': 'Tell us about your project or inquiry...',
    'contacts.form.send': 'Send Message',
    'contacts.training.enrollment': 'Training Program Enrollment',
    'contacts.training.enrollment.desc': 'Register your interest in our professional training programs.',
    'contacts.training.name': 'Full Name',
    'contacts.training.name.placeholder': 'Your full name',
    'contacts.training.email.placeholder': 'your.email@example.com',
    'contacts.training.organization': 'Organization',
    'contacts.training.organization.placeholder': 'Your organization or institution',
    'contacts.training.program': 'Select Program',
    'contacts.training.program.placeholder': 'Select training program',
    'contacts.training.adherence': 'Promotion of Treatment Adherence',
    'contacts.training.leadership': 'Leadership in Healthcare',
    'contacts.training.qualitative': 'Qualitative Research Methods',
    'contacts.training.custom': 'Custom Training (specify in comments)',
    'contacts.training.comments': 'Additional Comments',
    'contacts.training.comments.placeholder': 'Any specific requirements or questions about the training?',
    'contacts.training.submit': 'Submit Enrollment',
    'contacts.cta.title': 'Ready to Start Your Project?',
    'contacts.cta.desc': 'Whether you need research support, training programs, clinical services, or digital solutions, our team is ready to help you achieve your goals with evidence-based approaches.',
    'contacts.response.title': 'Quick Response',
    'contacts.response.desc': 'We typically respond to inquiries within 24 hours during business days.',
    'contacts.direct.title': 'Direct Communication',
    'contacts.direct.desc': 'Reach out directly to geral@ubkir.pt for immediate assistance.',
    'contacts.visit.title': 'Visit Us',
    'contacts.visit.desc': 'Schedule an in-person consultation at our Painho office.',
    
    // Footer
    'footer.company': 'UBKIR',
    'footer.description': 'Unbreakable Idea Research - Advancing Health Through Innovation, Research, and Education',
    'footer.contactInfo': 'Contact Info',
    'footer.services': 'Services',
    'footer.research': 'Research Activities',
    'footer.training': 'Training Programs',
    'footer.clinical': 'Clinical Services',
    'footer.editorial': 'Editorial Services',
    'footer.rights': '© 2024 Unbreakable Idea Research. All rights reserved.',
  },
  pt: {
    // Navigation
    'nav.home': 'Início',
    'nav.about': 'Sobre Nós',
    'nav.services': 'Serviços',
    'nav.training': 'Formação',
    'nav.clinical': 'Clínica',
    'nav.research': 'Investigação',
    'nav.digital': 'Desenvolvimento Digital',
    'nav.publishing': 'Publicação Acendalha',
    'nav.team': 'Equipa',
    'nav.contacts': 'Contactos',
    
    // Home page
    'home.hero.title': 'Unbreakable Idea Research',
    'home.hero.subtitle': 'Promovendo a Saúde Através da Inovação, Investigação e Educação',
    'home.hero.services': 'Os Nossos Serviços',
    'home.hero.learn': 'Saber Mais',
    'home.expertise.title': 'As Nossas Áreas de Especialização',
    'home.expertise.subtitle': 'Soluções abrangentes para investigação em saúde, educação e inovação',
    'home.research.title': 'Atividades de Investigação',
    'home.research.desc': 'Investigação quantitativa e qualitativa, análise estatística e visualização de dados',
    'home.training.title': 'Programas de Formação',
    'home.training.desc': 'Desenvolvimento de liderança, comunicação em saúde e formação em metodologia de investigação',
    'home.clinical.title': 'Serviços Clínicos',
    'home.clinical.desc': 'Terapia cognitivo-comportamental, avaliação psicológica e tratamentos especializados',
    'home.editorial.title': 'Serviços Editoriais',
    'home.editorial.desc': 'Publicação científica e de ficção científica através da Acendalha Publishing',
    'home.innovation.title': 'Liderando a Inovação na Investigação em Saúde',
    'home.innovation.desc1': 'Sob a liderança do CEO Osvaldo Santos, um renomado psicólogo clínico e da saúde, a UBKIR combina metodologias de investigação de vanguarda com aplicações práticas em cuidados de saúde, educação e inovação digital.',
    'home.innovation.desc2': 'A nossa abordagem multidisciplinar garante soluções abrangentes que fazem a ponte entre a investigação académica e os desafios reais dos cuidados de saúde.',
    'home.innovation.team': 'Conheça a Nossa Equipa',
    'home.stats.years': 'Anos de Experiência',
    'home.stats.projects': 'Projetos de Investigação',
    'home.cta.title': 'Pronto para Colaborar?',
    'home.cta.desc': 'Vamos discutir como a nossa experiência pode apoiar as suas necessidades de investigação, formação ou clínicas.',
    'home.cta.contact': 'Entre em Contacto',
    
    // About page
    'about.title': 'Sobre a UBKIR',
    'about.subtitle': 'Pioneiros em Investigação e Inovação nas Ciências da Saúde',
    'about.mission.title': 'A Nossa Missão',
    'about.mission.desc': 'Avançar as ciências da saúde através de metodologias de investigação inovadoras, programas de formação baseados em evidência e serviços clínicos abrangentes que fazem a ponte entre a excelência académica e as soluções práticas de cuidados de saúde.',
    'about.vision.title': 'A Nossa Visão',
    'about.vision.desc': 'Ser uma organização de investigação líder que transforma a prestação de cuidados de saúde através de investigação de ponta, educação e inovação digital, contribuindo para melhores resultados de saúde globalmente.',
    'about.values.title': 'Os Nossos Valores',
    'about.values.excellence': 'Excelência Científica',
    'about.values.excellence.desc': 'Compromisso com metodologias de investigação rigorosas e práticas baseadas em evidência',
    'about.values.innovation': 'Inovação',
    'about.values.innovation.desc': 'Abraçar novas tecnologias e metodologias para resolver desafios complexos de saúde',
    'about.values.collaboration': 'Colaboração',
    'about.values.collaboration.desc': 'Construir parcerias com profissionais de saúde, investigadores e instituições',
    'about.values.integrity': 'Integridade',
    'about.values.integrity.desc': 'Manter os mais altos padrões éticos em todas as nossas atividades de investigação e clínicas',
    
    // Services page
    'services.title': 'Os Nossos Serviços',
    'services.subtitle': 'Soluções abrangentes para investigação em saúde, formação e prática clínica',
    'services.research.title': 'Atividades de Investigação',
    'services.research.quant': 'Investigação Quantitativa',
    'services.research.quant.desc': 'Inquéritos, análise estatística e visualização de dados incluindo desenvolvimento de dashboards',
    'services.research.qual': 'Investigação Qualitativa',
    'services.research.qual.desc': 'Grupos focais, entrevistas em profundidade, World Cafés e construção de consenso através de painéis Delphi',
    'services.research.specialized': 'Investigação Especializada',
    'services.research.specialized.desc': 'Análise psicométrica, investigação de evidência do mundo real e investigação de marketing',
    'services.training.title': 'Programas de Formação',
    'services.training.leadership': 'Desenvolvimento de Liderança',
    'services.training.leadership.desc': 'Programas especializados para equipas de profissionais de saúde e gestão de cuidados de saúde',
    'services.training.communication': 'Comunicação em Saúde',
    'services.training.communication.desc': 'Estratégias de comunicação eficazes para ambientes de cuidados de saúde e envolvimento de pacientes',
    'services.training.methods': 'Métodos de Investigação',
    'services.training.methods.desc': 'Formação abrangente em metodologias de investigação qualitativa e quantitativa',
    'services.clinical.title': 'Serviços Clínicos',
    'services.clinical.therapy': 'Terapia Cognitivo-Comportamental',
    'services.clinical.therapy.desc': 'Intervenções terapêuticas baseadas em evidência para várias condições psicológicas',
    'services.clinical.specialized': 'Tratamentos Especializados',
    'services.clinical.specialized.desc': 'Distúrbios alimentares, depressão, ansiedade, adaptação a doenças crónicas e terapia de casal',
    'services.digital.title': 'Desenvolvimento Digital',
    'services.digital.desc': 'Software relacionado com saúde e soluções digitais para melhorar a prestação de cuidados de saúde e capacidades de investigação',
    'services.publishing.title': 'Publicação Acendalha',
    'services.publishing.desc': 'Serviços editoriais para publicações científicas e literatura de ficção científica',
    
    // Team page
    'team.title': 'A Nossa Equipa',
    'team.subtitle': 'Conheça os especialistas que impulsionam a inovação na UBKIR',
    'team.expertise.title': 'A Nossa Especialização Coletiva',
    'team.expertise.research': 'Excelência em Investigação',
    'team.expertise.research.desc': 'Metodologias avançadas em investigação quantitativa e qualitativa nas ciências da saúde.',
    'team.expertise.clinical': 'Prática Clínica',
    'team.expertise.clinical.desc': 'Intervenções terapêuticas baseadas em evidência e experiência em avaliação psicológica.',
    'team.expertise.training': 'Formação e Educação',
    'team.expertise.training.desc': 'Programas de desenvolvimento profissional e formação académica em ciências da saúde.',
    'team.expertise.publishing': 'Publicação e Inovação',
    'team.expertise.publishing.desc': 'Excelência editorial e inovação digital em tecnologias relacionadas com a saúde.',
    'team.partnership.title': 'Parceria com o Laboratório EnviHeB',
    'team.partnership.desc': 'Através da liderança do Dr. Osvaldo Santos no Laboratório EnviHeB no ISAMB, a UBKIR mantém fortes conexões com investigação académica de ponta e redes de colaboração internacional.',
    'team.partnership.leadership': 'Liderança em Investigação',
    'team.partnership.leadership.desc': 'Liderar projetos de investigação inovadores em saúde ambiental e comportamento.',
    'team.partnership.network': 'Rede Académica',
    'team.partnership.network.desc': 'Fortes conexões com instituições de investigação nacionais e internacionais.',
    'team.partnership.impact': 'Impacto das Publicações',
    'team.partnership.impact.desc': 'Publicações de investigação de alto impacto que contribuem para o conhecimento global da saúde.',
    'team.specializations.title': 'Especializações Profissionais',
    'team.cta.title': 'Trabalhe com a Nossa Equipa de Especialistas',
    'team.cta.desc': 'Pronto para colaborar com especialistas líderes em investigação em saúde e psicologia clínica? Contacte-nos para discutir as suas necessidades de projeto ou serviço.',
    'team.cta.button': 'Iniciar uma Conversa',
    
    // Contacts page
    'contacts.title': 'Contacte-nos',
    'contacts.subtitle': 'Entre em contacto com a nossa equipa',
    'contacts.office.title': 'Visite o Nosso Escritório',
    'contacts.office.address': 'Morada',
    'contacts.map.placeholder': 'Mapa interativo com vista satélite em breve',
    'contacts.map.note': '(Requer integração Supabase para funcionalidade completa)',
    'contacts.info.title': 'Informações de Contacto',
    'contacts.email': 'Email',
    'contacts.hours.title': 'Horário de Funcionamento',
    'contacts.hours.monday': 'Segunda - Sexta: 9:00 - 18:00',
    'contacts.hours.saturday': 'Sábado: 9:00 - 13:00',
    'contacts.hours.sunday': 'Domingo: Fechado',
    'contacts.general.title': 'Consulta Geral',
    'contacts.general.desc': 'Envie-nos uma mensagem sobre os nossos serviços ou questões gerais.',
    'contacts.alert': 'A funcionalidade de email requer integração Supabase para estar totalmente operacional.',
    'contacts.form.firstName': 'Primeiro Nome',
    'contacts.form.lastName': 'Último Nome',
    'contacts.form.firstName.placeholder': 'O seu primeiro nome',
    'contacts.form.lastName.placeholder': 'O seu último nome',
    'contacts.form.email': 'Endereço de Email',
    'contacts.form.email.placeholder': 'seu.email@exemplo.com',
    'contacts.form.subject': 'Assunto',
    'contacts.form.subject.placeholder': 'Selecionar tipo de consulta',
    'contacts.form.subject.research': 'Serviços de Investigação',
    'contacts.form.subject.training': 'Programas de Formação',
    'contacts.form.subject.clinical': 'Serviços Clínicos',
    'contacts.form.subject.digital': 'Desenvolvimento Digital',
    'contacts.form.subject.publishing': 'Serviços de Publicação',
    'contacts.form.subject.collaboration': 'Colaboração',
    'contacts.form.subject.other': 'Outro',
    'contacts.form.message': 'Mensagem',
    'contacts.form.message.placeholder': 'Conte-nos sobre o seu projeto ou consulta...',
    'contacts.form.send': 'Enviar Mensagem',
    'contacts.training.enrollment': 'Inscrição em Programa de Formação',
    'contacts.training.enrollment.desc': 'Registe o seu interesse nos nossos programas de formação profissional.',
    'contacts.training.name': 'Nome Completo',
    'contacts.training.name.placeholder': 'O seu nome completo',
    'contacts.training.email.placeholder': 'seu.email@exemplo.com',
    'contacts.training.organization': 'Organização',
    'contacts.training.organization.placeholder': 'A sua organização ou instituição',
    'contacts.training.program': 'Selecionar Programa',
    'contacts.training.program.placeholder': 'Selecionar programa de formação',
    'contacts.training.adherence': 'Promoção da Adesão ao Tratamento',
    'contacts.training.leadership': 'Liderança em Cuidados de Saúde',
    'contacts.training.qualitative': 'Métodos de Investigação Qualitativa',
    'contacts.training.custom': 'Formação Personalizada (especificar nos comentários)',
    'contacts.training.comments': 'Comentários Adicionais',
    'contacts.training.comments.placeholder': 'Algum requisito específico ou questões sobre a formação?',
    'contacts.training.submit': 'Submeter Inscrição',
    'contacts.cta.title': 'Pronto para Iniciar o Seu Projeto?',
    'contacts.cta.desc': 'Quer precise de apoio em investigação, programas de formação, serviços clínicos ou soluções digitais, a nossa equipa está pronta para o ajudar a alcançar os seus objetivos com abordagens baseadas em evidência.',
    'contacts.response.title': 'Resposta Rápida',
    'contacts.response.desc': 'Normalmente respondemos a consultas dentro de 24 horas durante os dias úteis.',
    'contacts.direct.title': 'Comunicação Direta',
    'contacts.direct.desc': 'Contacte diretamente geral@ubkir.pt para assistência imediata.',
    'contacts.visit.title': 'Visite-nos',
    'contacts.visit.desc': 'Agende uma consulta presencial no nosso escritório em Painho.',
    
    // Footer
    'footer.company': 'UBKIR',
    'footer.description': 'Unbreakable Idea Research - Promovendo a Saúde Através da Inovação, Investigação e Educação',
    'footer.contactInfo': 'Informações de Contacto',
    'footer.services': 'Serviços',
    'footer.research': 'Atividades de Investigação',
    'footer.training': 'Programas de Formação',
    'footer.clinical': 'Serviços Clínicos',
    'footer.editorial': 'Serviços Editoriais',
    'footer.rights': '© 2024 Unbreakable Idea Research. Todos os direitos reservados.',
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('en');

  // Load language preference from localStorage on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem('ubkir-language') as Language;
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'pt')) {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('ubkir-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};